<div class="container">
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info" >
            <div class="panel-heading">
                <div class="panel-title">Login Page</div>
            </div>
            <div style="padding-top:15px" class="panel-body" >
                <form id="loginform" class="form-horizontal" role="form" action="admin/login" method="post">
                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input id="login-username" type="text" class="form-control" name="login"
                        placeholder="username" required>
                    </div>
                    <div style="margin-bottom: 5px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input id="login-password" type="password" class="form-control" name="password"
                        placeholder="password" required>
                    </div>
                    <div style="margin-top:15px; " class="form-group">
                            <!-- Button -->
                        <div class="col-sm-12 controls">
                          <button type="submit" class="btn btn-success">Login</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
